# Generated by Django 4.1.4 on 2023-01-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
