# Generated by Django 4.1.4 on 2023-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRmaker', '0003_alter_filldetails_document_alter_filldetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filldetails',
            name='document',
        ),
        migrations.AlterField(
            model_name='filldetails',
            name='image',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
        migrations.AlterField(
            model_name='filldetails',
            name='preferredJL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
